# Generated by Django 4.0.5 on 2022-06-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceConseilApp', '0003_remove_service_label_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Testimonial', models.CharField(max_length=50)),
                ('works_Testimonial', models.CharField(max_length=50)),
                ('comment_Testimonial', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
