# Generated by Django 4.0.5 on 2022-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceConseilApp', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image_Testimonial',
            field=models.FileField(default=1, upload_to='img_testimonial'),
            preserve_default=False,
        ),
    ]
