# Generated by Django 4.0.5 on 2022-06-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceConseilApp', '0005_testimonial_image_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_name_team',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
