# Generated by Django 4.0.5 on 2022-06-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceConseilApp', '0006_team_last_name_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseau_social_team',
            old_name='facebook_team',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='reseau_social_team',
            old_name='linkedin_team',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='reseau_social_team',
            old_name='twitter_team',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='reseau_social',
        ),
        migrations.AddField(
            model_name='reseau_social_team',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serviceConseilApp.team'),
            preserve_default=False,
        ),
    ]
