# Generated by Django 4.0.5 on 2022-06-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceConseilApp', '0007_rename_facebook_team_reseau_social_team_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseau_social_team',
            name='icon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reseau_social_team',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
