# Generated by Django 4.0.5 on 2022-06-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_info',
            name='phone_site',
            field=models.CharField(max_length=15),
        ),
    ]
