# Generated by Django 4.0.5 on 2022-06-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_alter_site_info_phone_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Label_about',
            new_name='title_about',
        ),
    ]
