# Generated by Django 4.0.5 on 2022-06-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_rename_label_about_about_title_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_about',
            new_name='Potentialite',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Type_About',
        ),
        migrations.RemoveField(
            model_name='about',
            name='feature',
        ),
    ]
