# Generated by Django 4.0.5 on 2022-06-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_about_image_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='potentialite',
            old_name='Icon_Type_about',
            new_name='Icon',
        ),
        migrations.RenameField(
            model_name='potentialite',
            old_name='description_Type_about',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='potentialite',
            old_name='title_Type_about',
            new_name='title',
        ),
        migrations.AddField(
            model_name='feature',
            name='potentialite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webApp.potentialite'),
            preserve_default=False,
        ),
    ]
