# Generated by Django 4.0.5 on 2022-06-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_rename_description_feature_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='potentialite',
        ),
    ]
