# Generated by Django 4.0.5 on 2022-06-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0007_remove_feature_potentialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject_contact',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
